# Generated by Django 5.0.3 on 2024-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.IntegerField(blank=True, default=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/skills')),
                ('is_key_skill', models.BooleanField(default=False)),
            ],
        ),
    ]
